### ISSUE TITLE
Any reason to not add helper functions?

### ISSUE THREAD

**Issue by josejuan** [chordify/currency-codes#1]
Hello,

functions like `lookupByCode :: Int -> Maybe Currency` (and `lookupByAlpha`) may be useful. I see `fromAlpha` into README but not helpers into `Data.Currency`, any reason?

Thank you!

**Comment by KtorZ** [comment]
Well, given the list of all currencies, filtering functions are quite straightforward to write. It's also quite hard to cover all possible cases and needs of people so I find that exposing the list keeps it flexible enough. 

Maybe we could simply offer fromAlpha, fromNumeric etc ... but they are very simple and the API may not cover your need (maybe one prefers an `Either` instead of a `Maybe` or one wants it to throws if not found etc ...).

**Comment by josejuan** [comment]
Mmm... I understand, anyway I think that helpers are "natural" actions over `currencies`, and easy to keep into your own stack, even the "unsafe" version (throwing some fail message if not exists) is useful in general, e.g.

    currency :: Parser Currency
    currency = nat >>= lookupByNumeric'

e.g.

    > parse currency "Currency" "978"
    Right (Currency {alpha = EUR, numeric = 978, minor = 2, name = "Euro"})
    > parse currency "Currency" "9178"
    Left "Currency" (line 1, column 4):
    The currency code `917` is unknown

Thank you anyway!
